#!/bin/bash

if [[ ! -e volundr ]]
then
    make
fi

ulimit -c unlimited
export LD_LIBRARY_PATH=./vlibs/elf:./vlibs/common:./vlibs/asm
#strace ./volundr $*;
#valgrind ./volundr $*;
#gdb ./volundr $*;
./volundr $*;
